<a href="https://colab.research.google.com/github/varunbhoyar133-png/Feature_Extraction_Project-Pandas-/blob/main/FeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
# #which is the longest running anime

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r'/content/anime.csv')

In [ ]:
df.head()

In [6]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [28]:
# make a new column for episode count
def extract_eps(txt):
  check = False
  data = ''
  for i in txt:
    if i== ')':
      check = False
      return data
    if check == True:
      data = data+i
    if i =='(':
      check = True

In [33]:
df

,Rank,Title,Score,Episode,Episodes,Episodes_from_Title
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,64 eps,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,24 eps,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,13 eps,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,51 eps,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,10 eps,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,51 eps,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,1 eps,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,148 eps,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,13 eps,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,13 eps,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,2 eps,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,110 eps,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,13 eps,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,13 eps,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,12 eps,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,201 eps,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,1 eps,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,22 eps,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,24 eps,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,25 eps,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,1 eps,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,1 eps,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,7 eps,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,14 eps,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,74 eps,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,1 eps,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,1 eps,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,12 eps,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,1 eps,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,24 eps,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,23 eps,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,12 eps,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,26 eps,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,13 eps,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,16 eps,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,11 eps,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,1 eps,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,11 eps,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,10 eps,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,1 eps,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,26 eps,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,12 eps,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,75 eps,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,26 eps,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,26 eps,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,24 eps,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,10 eps,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,12 eps,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,12 eps,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,4 eps,4

In [34]:
df = df.drop(['Episode','Episodes_from_Title'], axis=1)

In [36]:
df['Episodes'] = df['Episodes'].str.replace(' eps','')

In [37]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

In [38]:
#make a new column for time stamp
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [51]:
def timestamp(txt):
  check = False
  data = ''
  for i in txt:
    if len(data)== 19:
      return data
    if check == True:
      data = data+i
    if i==')':
      check = True

In [52]:
df["TimeStamp"]= df['Title'].apply(timestamp)

In [53]:
df

,Rank,Title,Score,Episodes,TimeStamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [55]:
# which anime has the highest score
df.head()

,Rank,Title,Score,Episodes,TimeStamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [60]:
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [61]:
#give me top 5 highest scoring anime
df.head()

,Rank,Title,Score,Episodes,TimeStamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [ ]:
df[df['Score'] == df['Score'].max()]['Title']